name: Release
on:
  workflow_dispatch:
  push:
    tags:
      -'v*'
env:
  PROJECT_PATH: $GITHUB_WORKSPACE/src/SourceGenerator.Foundations/SourceGenerator.Foundations.csproj
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      # CheckOut 
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      # Restore
      - name: Restore dependencies
        run: dotnet restore $PROJECT_PATH
      # Build
      - name: Build
        run: dotnet build $PROJECT_PATH --no-restore
      # Test
      - name: Test
        run: dotnet test $PROJECT_PATH --no-build --verbosity normal
      # Create Github Release
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: MyReleaseMessage
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: $PROJECT_PATH 

          # Platform target to compile (default is empty/AnyCPU)
          BUILD_PLATFORM: x64
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: SourceGenerator.Foundations

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
